### ISSUE TITLE
CDE: Google Sheets Sample Data and Templates

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#345]
# CDE: Google Sheets Sample Data and Templates Needed

Hi @J-Yash, I am tasking you with providing sample files and templates in Google Sheets for the Cell Distance Explorer. Let me know if there is anyone else I need to loop in to complete this task.

Please use this GitHub comment thread for uploading files. Bruce, Daniel, or Edward can close out this issue when development has what they need.

## Requirements
- Share all sheets in the [Google Drive folder: Cell Distance Explorer](https://drive.google.com/drive/folders/1JdOla1IM4_zT7Z62OD0hhcXDFqtrUWvn)
  - Individually grant view access for each Google Sheet. The CDE folder and its directory can't be made public.
- Collaborate with development as needed to complete this task

## Resources
- [FigJam: UX Studies: Bruce, Yash, and Libby's Comment thread on Files](https://www.figma.com/file/Azw0jLJH3Cfd5tlM3iX95x?type=whiteboard&node-id=785-758#752062171)
- [Google Drive: CDE Folder](https://drive.google.com/drive/folders/1JdOla1IM4_zT7Z62OD0hhcXDFqtrUWvn)

### Sample Files
Sample files are needed to explore visualizations. The below were specified in Figma:
- [ ] 2D Skin
- [ ] 3D Intestine

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/aa56831a-7b9f-4f07-8555-3ac5c396788e)

### Templates for the Create Visualization workflow
- [ ] Cell Type Table (note: Katy wants endothelial cells and a couple of other rows of sample data loaded into this template)
- [ ] Color Map Table

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/41441888-29fb-4411-b095-23f3996b646f)
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/010df8e4-780f-49e8-9c9d-098b9cbddfd0)

**Comment by J-Yash** [comment]
@LibbyUX 
* The two template files have been uploaded to the Google Drive mentioned above. I have granted view access for both files. Feel free to update the color map template file based on how such a file would be used as input.
* The sample files for intestine and skin data are already on S3 image-store:
    * 2D intestine sample:  `vccf-data-cell-nodes/published/intestine-codex-stanford/B006_Ascending-nodes.csv`
    * 3D skin sample: `vccf-data-cell-nodes/published/skin-celldive-ge/region_6-nodes.csv`

**Comment by LibbyUX** [comment]
Thank you so much for the speedy reply and the templates, @J-Yash!

I have follow-up questions about the sample files:
- I am unfamiliar with the S3 image-store, can you provide a link to this? Is this something our development team is tracking and familiar with, so I shouldn't worry about it?
- Do the sample files contain all metadata fields being reported in the specified Metadata module?
- In the Metadata Module: Clicking on the Source Data sample file title routes users to the sample file's Google Sheet.

View the design for the Sample Metadata module below or in the [Figma design file](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=605-17419&mode=design&t=AIyT42L4hZc40OjN-4).

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/3923b49b-8ac5-436f-8f82-a43c2924a6df)

**Comment by J-Yash** [comment]
Hey @LibbyUX , 
Dev team should be able to get the sample files from S3. But here are the links as well:

- Intestine 2D: https://cdn.humanatlas.io/image-store/vccf-data-cell-nodes/published/intestine-codex-stanford/B006_Ascending-nodes.csv 
- Skin 3D: https://cdn.humanatlas.io/image-store/vccf-data-cell-nodes/published/skin-celldive-ge/region_6-nodes.csv

Note that the sample files only contain the cell coordinates and cell types. They do not contain the metadata since that is not part of the file format for nodes files. Below is the metadata for the two samples:

Intestine 2D:
Organ: Intestine
Technology: CODEX
Thickness: 7
Pixel Size: 0.866

Skin 3D:
Organ: Skin
Technology: Cell DIVE
Thickness: 5
Pixel Size: 0.325

`In the Metadata Module: Clicking on the Source Data sample file title routes users to the sample file's Google Sheet.`
Does it route them to a Google Sheet or simply downloads the source CSV file from the link above? If the former, I will have to create two more Google Sheets (based on the same CSV files linked above).

**Comment by LibbyUX** [comment]
Hi @J-Yash, it should route them to a Google Sheet. Our experts were most comfortable viewing and using Google Sheets.

**Comment by J-Yash** [comment]
Hi @LibbyUX , I have placed the two sample files in the Google Drive linked above.

**Comment by LibbyUX** [comment]
Thank you so much, @J-Yash!

**Comment by LibbyUX** [comment]
Hi @bherr2, @edlu77, @axdanbol, @bhushankhope 

Do you have everything you need for this issue?

**Comment by bherr2** [comment]
We just made the data part of the repository
