### ISSUE TITLE
Source Data improvements

### ISSUE THREAD

**Issue by supriyabidanta** [hubmapconsortium/hra-ui#513]
I have provide the information in below format:
Authors | Title | DOI | Year

Yoshiharu Muto; Parker C. Wilson; Nicolas Ledru; Haojia Wu; Henrik Dimke; Sushrut S. Waikar; Benjamin D .Humphreys | Single cell transcriptional and chromatin accessibility profiling redefine cellular heterogeneity in the adult human kidney | https://doi.org/10.1038/s41467-021-22368-w |  2021

Zhong Yi Wang; Adrian Keogh; Annick Waldt; Rachel Cuttat; Marilisa Neri; Shanshan Zhu; Sven Schuierer; Alexandra Ruchti; Christophe Crochemore; Judith Knehr; Julie Bastien; Iwona Ksiazek; Daniel Sánchez Taltavull; Hui Ge; Jing Wu; Guglielmo Roma; Stephen B. Helliwell1; Deborah Stroka; Florian Nigsch | Single‑cell and bulk transcriptomics of the liver reveals potential targets of NASH with fibrosis | https://doi.org/10.1038/s41598-021-98806-y | 2021

Felipe A. Vieira Braga; Gozde Kar; Marijn Berg, Orestes A. Carpaij; Krzysztof Polanski; Lukas M. Simon; Sharon Brouwer; Tomas Gomes; Laura Hesse; Jian Jiang | A cellular census of human lungs identifies novel cell states in health and in asthma | https://doi.org/10.1038/s41591-019-0468-5 | 2019

**Comment by LibbyUX** [comment]
Hi team, I am building on this issue due to something else I caught with @supriyabidanta when we met yesterday:

I can't click either of the table text links in the source data section as it is. If table items use the [table text button component](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=2319-4362&t=3yTkV0MY1LkgR0Ln-4), they need to function as buttons with open-in-new tab functionality. Please use normal text if we don't have links to source data.

Additionally, I have some cosmetic/responsive updates to squeeze in to prep for redesigning the UI entirely.

## To summarize, please:
- [ ] Add the data sources that Supriya has provided on this issue
- [ ] Use [table text button](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=2319-4363&t=3yTkV0MY1LkgR0Ln-4) to link out to data
  - If there no is link to a dataset, for now, please use Label Small: Metropolis Medium/500 12px/18px in HRA Primary Blue #201E3D
- [ ] Add max height of 276px to the [source data container](https://www.figma.com/design/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?node-id=5173-82610&t=fpr29vENVblBqVeN-4)
  - The matrix needs to stretch responsively
 
## Figma Resources
- FTU Explorer file: [Source Data Section 7.3.2024 Update](https://www.figma.com/design/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?node-id=5173-82610&t=fpr29vENVblBqVeN-4)
- Design System Repo: [Table Text Button](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=2319-4362&t=3yTkV0MY1LkgR0Ln-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/8745a9e3-c391-4259-8142-4d9333779a32)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/f68786b9-15c1-4bdc-8cf0-8ac43ba46021)

**Comment by LibbyUX** [comment]
@axdanbol & @edlu77 - Is it possible to knock this out today? I learned this morning that I must design an updated FTU Explorer UI annotation supplemental figure ASAP. This is for a paper that is being resubmitted. Please let me know if there is anything I can do to support you. Thank you so much!

**Comment by LibbyUX** [comment]
Thank you so much @edlu77 !
