### ISSUE TITLE
Remove contact button

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#531]
Hi team,

The contact button/modal in the FTU Explorer needs functional and aesthetic work, but we have bigger priorities right now.

Can we please remove the contact button for now as a quick short term fix?

I will provide updated specs for this component when I redesign this interface. Thanks!

<img width="1497" alt="Screenshot 2024-07-09 at 10 00 40 AM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/fd7690d8-5698-4bb1-b689-c11e00c12ae3">
<img width="777" alt="Screenshot 2024-07-09 at 10 00 55 AM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/93edd48f-3286-42b6-9201-a53ad50a670d">

**Comment by emquardokus** [comment]
@LibbyUX as a compromise, you could just remove the open diaglog window and make it work like the ASCT+B table contact button where it directly opens a form email into your email program.  That would be easiest? The behavior of opening a dialog wiindow seems to be the problem that is not correctly working.  It looks like there must be both code blocks in the code doing BOTH things rather than one or the other behavior.  BTW: it's already July (YIKES!!)

**Comment by LibbyUX** [comment]
Hey @emquardokus I want to keep things super simple for our team so I will loop back to this when I am redesigning the interface. I have a vision for all of our interfaces and Y3 is when we iron out the inconsistencies for sure! 

Thanks for understanding!

**Comment by bhushankhope** [comment]
Fixed this in PR #532
