### ISSUE TITLE
Update: humanatlas.io has Previews in two menus

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/hra-ui#663]
Previews exist in 2 places in menu as a submenu in the Training & Outreach and as a separate menu "Use HRA Previews"
Are they both necessary?
@bherr2 @LibbyUX 
<img width="655" alt="Screenshot 2024-08-21 at 1 12 32 PM" src="https://github.com/user-attachments/assets/99bf1f45-a49c-494a-829d-34a049bbe2cf">

https://humanatlas.io/overview-training-outreach#previews

https://humanatlas.io/overview-use-the-hra

**Comment by LibbyUX** [comment]
@emquardokus - No, it isn't necessary in my opinion. The request to create a navigation category called "Use HRA Previews" came from above me and unfortunately it makes things more confusing to anyone outside of our group.

Most brand new users don't know what a Preview is in relation to the HRA (let alone know what the HRA is). I have observed friends and family get confused immediately upon looking at this navigation structure and website layout.

Additionally, most of the Preview content in the Training & Outreach menu is stale. It should probably be removed. It wouldn't be an issue if this type of content was contained in a blog where it was timestamped so users could know how old it is.

Because we don't have design labor to redesign the current site's navigation, argue for a more intuitive navigation structure, and hand off an improved navigation structure, I will close this as not planned. The good news is that this has been addressed in new designs of humanatlas.io - There will not be hardcoded preview pages moving forward.
